<div class="card">
    <h2>Daftar Booking</h2>
    
    <!-- Search and Filter -->
    <div class="search-filter">
        <input type="text" id="searchInput" placeholder="Cari booking...">
    </div>
    
    <div class="table-responsive">
        <table id="bookingsTable">
            <thead>
                <tr>
                    <th>Ruangan</th>
                    <th>Tanggal</th>
                    <th>Waktu</th>
                    <th>Tujuan</th>
                    <th>Status</th>
                    <?php if (isAdmin()): ?>
                    <th>Aksi</th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = $bookings->fetch(PDO::FETCH_ASSOC)): ?>
                <tr>
                    <td><?php echo e($row['room_name']); ?></td>
                    <td><?php echo e(formatDate($row['date'])); ?></td>
                    <td><?php echo e(formatTime($row['start_time']) . ' - ' . formatTime($row['end_time'])); ?></td>
                    <td><?php echo e($row['purpose']); ?></td>
                    <td>
                        <span class="status-<?php echo e($row['status']); ?>">
                            <?php echo ucfirst(e($row['status'])); ?>
                        </span>
                    </td>
                    <?php if (isAdmin()): ?>
                    <td>
                        <?php if ($row['status'] == 'pending'): ?>
                        <form method="post" class="inline-form">
                            <input type="hidden" name="csrf_token" value="<?php echo generateCSRFToken(); ?>">
                            <input type="hidden" name="action" value="update_status">
                            <input type="hidden" name="booking_id" value="<?php echo e($row['id']); ?>">
                            <input type="hidden" name="status" value="approved">
                            <button type="submit" class="btn-success btn-sm">Setujui</button>
                        </form>
                        <form method="post" class="inline-form">
                            <input type="hidden" name="csrf_token" value="<?php echo generateCSRFToken(); ?>">
                            <input type="hidden" name="action" value="update_status">
                            <input type="hidden" name="booking_id" value="<?php echo e($row['id']); ?>">
                            <input type="hidden" name="status" value="rejected">
                            <button type="submit" class="btn-danger btn-sm">Tolak</button>
                        </form>
                        <?php endif; ?>
                    </td>
                    <?php endif; ?>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    </div>
    
    <!-- Pagination -->
    <div class="pagination" id="pagination">
        <!-- Pagination will be generated by JavaScript -->
    </div>
</div>